### PR TITLE
Sharv/us 480237

### PR DESCRIPTION
**Pull request by vishalshrm539**
Upgraded Angular from 11 to 13 since private methods aren’t supported in Angular 11 and also to keep the SDK updated with the latest Angular version.

### CODE REVIEW

**Comment by vishalshrm539** [comment]
Please refer [US-480237](https://agilestudio.pega.com/prweb/AgileStudio/app/agilestudio/story/US-480237) for more details.

**Review by JEAxero — APPROVED** [review]
I'll defer to @paulgagnon-pega for his expertise with Angular version upgrades but... I just ran some sample apps against this branch in dev and prod and it seems to be working fine.

**Comment by vrseraphin** [comment]
Notice a lint block was removed from angular.json.  Was that done by the automatic tooling run as part of the upgrades?  Does lint still work for SDK-A after changes?

**Comment by JEAxero** [comment]
re: lint comment

I don't think linting has ever worked with SDK-A. If/when we do linting with SDK-A, we should follow the pattern used in SDK-R to adopt the standard Pega @pega/configs, etc. dependencies.

**Review by paulgagnon-pega — APPROVED** [review]

**Pull request merged**
