### PR TITLE
Mashm/us 489575

### PR DESCRIPTION
**Pull request by 4manasa**
changes added
 -- modified the details component to render children of type reference
 -- modified details layout similar to react SDK
 --Added SingleReference and MultiReference components

### CODE REVIEW

**Review by JEAxero — CHANGES_REQUESTED** [review]
During my testing, when I try to clear a search, it doesn't clear the "Price".

**Comment by JEAxero** [comment]
Also, I noticed that the MultiSelectReadOnly emits a "Table is readOnly." string above the table. This should be removed.

**Comment by 4manasa** [comment]
> Also, I noticed that the MultiSelectReadOnly emits a "Table is readOnly." string above the table. This should be removed.

remove the text and updated the PR

**Comment by 4manasa** [comment]
> During my testing, when I try to clear a search, it doesn't clear the "Price".

fixed this issue and updated the PR.

**Review by JEAxero — APPROVED** [review]
Thanks for the updates.

**Pull request merged**
