### PR TITLE
Added tests for SingleRecord mode in Query

### PR DESCRIPTION
**Pull request by vishalshrm539**
* Added tests for SingleRecord mode in Query as SingleRecord test-case is now fixed in Digv2 app.

### CODE REVIEW

**Review by JEAxero — APPROVED** [review]
Ran tests and looks ok to me.

**Comment by JEAxero** [comment]
> Ran tests and looks ok to me.

But noticing that one of the actions is failing. So, that will need to be fixed before we can merge this change.

**Comment by vishalshrm539** [comment]
> > Ran tests and looks ok to me.
> 
> But noticing that one of the actions is failing. So, that will need to be fixed before we can merge this change.



> > Ran tests and looks ok to me.
> 
> But noticing that one of the actions is failing. So, that will need to be fixed before we can merge this change.



> > Ran tests and looks ok to me.
> 
> But noticing that one of the actions is failing. So, that will need to be fixed before we can merge this change.

Yes, looking at it.

**Comment by vishalshrm539** [comment]
> > Ran tests and looks ok to me.
> 
> But noticing that one of the actions is failing. So, that will need to be fixed before we can merge this change.

Checking it.

**Comment by vishalshrm539** [comment]
> > > Ran tests and looks ok to me.
> > 
> > 
> > But noticing that one of the actions is failing. So, that will need to be fixed before we can merge this change.
> 
> Checking it.

Upgrading Playwright fixed this issue.

**Pull request merged**
